name = "umami"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "umami-db"
database_id = "1fecd4f4-e839-4143-b6ae-e72e55313034"

[[kv_namespaces]]
binding = "KV"
id = "aaa7e56746144cf8866f8b50284efc67"

[assets]
directory = "./public"
binding = "ASSETS"

[dev]
port = 3001
local_protocol = "http"

[observability.logs]
enabled = true
